# .github/workflows/ci.yml

name: CI/CD for WordPress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Chọn phiên bản PHP phù hợp với WordPress của bạn

    - name: Install dependencies
      run: sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev

    - name: Install Composer
      run: curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer

    - name: Install npm
      run: sudo apt-get install -y npm

    - name: Install WordPress dependencies
      run: npm install

    
    - name: Set up MySQL
      uses: mysql-actions/setup-mysql@v1
      with:
        mysql-version: '5.7'
        mysql-root-user: 'root'
        mysql-root-password: ''
        mysql-database: 'mydata'

    - name: Install WordPress
      run: |
        wget https://wordpress.org/latest.tar.gz
        tar -xzf latest.tar.gz
        mv wordpress/* .
        cp wp-config-sample.php wp-config.php
        sed -i "s/database_name_here/mydata/" wp-config.php
        sed -i "s/username_here/root/" wp-config.php
        sed -i "s/password_here//" wp-config.php
        php -S localhost:8084 &

    
