name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install


    - name: Show changes
      run: |
        echo "Changes in the latest commit:"
        git diff HEAD~1 HEAD

    - name: Notify about changes
      run: echo "Code has been pushed to main branch"
