name: Deploy WordPress Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to XAMPP
      run: |
        # Copy files to XAMPP htdocs directory (adjust the path as needed)
        robocopy .\ D:\DOWLOAD\Xxam\htdocs\wordpress

