name: CI/CD for WordPress with XAMPP

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có push lên nhánh main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout mã nguồn từ repository

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Sử dụng PHP version 7.4, thay đổi nếu cần thiết

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Install wp-cli
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Set up WordPress configuration
        run: |
          cd wordpress
          wp config create --dbname=mydata --dbuser=root --dbpass= --dbhost=localhost --allow-root

      - name: Install WooCommerce plugin
        run: |
          wp plugin install woocommerce --activate --allow-root

      - name: Run PHP linting
        run: |
          find . -name "*.php" -exec php -l {} \;

      - name: Run WordPress Coding Standards check
        run: |
          wp theme review check . --allow-root

      
