name: CI/CD for WordPress with XAMPP

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có push lên nhánh main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout mã nguồn từ repository

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Sử dụng PHP version 7.4, thay đổi nếu cần thiết

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Set up WordPress
        run: |
          cp -r ./wordpress/* /opt/lampp/htdocs/wordpress  # Copy mã nguồn WordPress vào thư mục của XAMPP
          cd /opt/lampp/htdocs/wordpress
          wp core download --allow-root
          wp config create --dbname=wordpress --dbuser=root --dbpass= --dbhost=localhost --allow-root
          wp core install --url=http://localhost/wordpress --title="My WordPress Site" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --allow-root

      - name: Install WooCommerce plugin
        run: |
          wp plugin install woocommerce --activate --allow-root

      - name: Run PHP linting (optional)
        run: |
          find . -name "*.php" -exec php -l {} \;

      - name: Deploy to local server
        run: |
          # Add deployment commands here if needed, e.g., starting XAMPP

      - name: Notify deployment status
        run: |
          echo "Deployment completed successfully"
