# .github/workflows/ci.yml

name: CI/CD for WordPress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydata
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Chọn phiên bản PHP phù hợp với WordPress của bạn

    - name: Install dependencies
      run: sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev

    - name: Install Composer
      run: curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          echo 'Waiting for MySQL...'
          sleep 5
        done

    - name: Copy WordPress files
      run: |
        rsync -av wordpress/ ./wordpress_deploy/
        cp wp-config.php wordpress_deploy/wp-config.php
        sed -i "s/database_name_here/mydata/" wordpress_deploy/wp-config.php
        sed -i "s/username_here/root/" wordpress_deploy/wp-config.php
        sed -i "s/password_here//" wordpress_deploy/wp-config.php

    - name: Wait for server to start
      run: sleep 30

    

    - name: Display server logs if the test fails
      if: failure()
      run: cat server.log
