name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    

    - name: Show changes
      run: |
        git fetch origin
        git log -1 --pretty=format:"%h - %an, %ar : %s"

    - name: Notify about changes
      run: echo "Code has been pushed to main branch"
