name: Deploy WordPress Site

on:
  push:
    branches:
      - main  # Cấu hình workflows sẽ chạy khi có push lên nhánh main

jobs:
  deploy:
    runs-on: window-latest  # Sử dụng Ubuntu runner

    steps:
    - name: Checkout code  # Bước này để checkout mã nguồn từ repository GitHub
      uses: actions/checkout@v2
      
    

   
